### ISSUE TITLE
DatePicker don't work on Vue3

### ISSUE THREAD

**Issue by blaryj** [nathanreyes/v-calendar#1049]
I try to migrate my app to Vue3, so I use v-calendar@next
This is my (simplified) component:

```js
<template>
    <DatePicker v-model="rawDate" />
</template>

<script>
    import { DatePicker } from 'v-calendar';

    export default {
        components: {DatePicker},

        data: () => ({
            rawDate: new Date(),
        })
    };
</script>
```
and errors in browser
```
Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:790 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at callWithErrorHandling (vue.runtime.esm-bundler.js:1606:1)
    at callWithAsyncErrorHandling (vue.runtime.esm-bundler.js:1612:1)
    at job (vue.runtime.esm-bundler.js:3778:1)
    at ReactiveEffect.scheduler (vue.runtime.esm-bundler.js:3811:1)
    at triggerEffects (vue.runtime.esm-bundler.js:689:1)
    at trigger (vue.runtime.esm-bundler.js:659:1)
    at Object.set (vue.runtime.esm-bundler.js:806:1)
    at Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:981:1
    at Proxy.forEach (<anonymous>)
    at Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:948:1
refreshPages @ Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:790
created @ Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:566
callWithErrorHandling @ vue.runtime.esm-bundler.js:1603
callWithAsyncErrorHandling @ vue.runtime.esm-bundler.js:1612
callHook @ vue.runtime.esm-bundler.js:4999
applyOptions @ vue.runtime.esm-bundler.js:4887
finishComponentSetup @ vue.runtime.esm-bundler.js:10428
setupStatefulComponent @ vue.runtime.esm-bundler.js:10325
setupComponent @ vue.runtime.esm-bundler.js:10255
mountComponent @ vue.runtime.esm-bundler.js:7561
processComponent @ vue.runtime.esm-bundler.js:7532
patch @ vue.runtime.esm-bundler.js:7124
componentUpdateFn @ vue.runtime.esm-bundler.js:7679
run @ vue.runtime.esm-bundler.js:491
setupRenderEffect @ vue.runtime.esm-bundler.js:7810
mountComponent @ vue.runtime.esm-bundler.js:7578
processComponent @ vue.runtime.esm-bundler.js:7532
patch @ vue.runtime.esm-bundler.js:7124
componentUpdateFn @ vue.runtime.esm-bundler.js:7679
run @ vue.runtime.esm-bundler.js:491
setupRenderEffect @ vue.runtime.esm-bundler.js:7810
mountComponent @ vue.runtime.esm-bundler.js:7578
processComponent @ vue.runtime.esm-bundler.js:7532
patch @ vue.runtime.esm-bundler.js:7124
mountChildren @ vue.runtime.esm-bundler.js:7320
mountElement @ vue.runtime.esm-bundler.js:7229
processElement @ vue.runtime.esm-bundler.js:7201
patch @ vue.runtime.esm-bundler.js:7121
mountChildren @ vue.runtime.esm-bundler.js:7320
mountElement @ vue.runtime.esm-bundler.js:7229
processElement @ vue.runtime.esm-bundler.js:7201
patch @ vue.runtime.esm-bundler.js:7121
mountChildren @ vue.runtime.esm-bundler.js:7320
mountElement @ vue.runtime.esm-bundler.js:7229
processElement @ vue.runtime.esm-bundler.js:7201
patch @ vue.runtime.esm-bundler.js:7121
componentUpdateFn @ vue.runtime.esm-bundler.js:7679
run @ vue.runtime.esm-bundler.js:491
setupRenderEffect @ vue.runtime.esm-bundler.js:7810
mountComponent @ vue.runtime.esm-bundler.js:7578
processComponent @ vue.runtime.esm-bundler.js:7532
patch @ vue.runtime.esm-bundler.js:7124
mountChildren @ vue.runtime.esm-bundler.js:7320
mountElement @ vue.runtime.esm-bundler.js:7229
processElement @ vue.runtime.esm-bundler.js:7201
patch @ vue.runtime.esm-bundler.js:7121
patchBlockChildren @ vue.runtime.esm-bundler.js:7441
patchElement @ vue.runtime.esm-bundler.js:7349
processElement @ vue.runtime.esm-bundler.js:7204
patch @ vue.runtime.esm-bundler.js:7121
componentUpdateFn @ vue.runtime.esm-bundler.js:7758
run @ vue.runtime.esm-bundler.js:491
callWithErrorHandling @ vue.runtime.esm-bundler.js:1603
flushJobs @ vue.runtime.esm-bundler.js:1842
Promise.then (asynchrone)
queueFlush @ vue.runtime.esm-bundler.js:1733
queueJob @ vue.runtime.esm-bundler.js:1727
(anonyme) @ vue.runtime.esm-bundler.js:7793
triggerEffects @ vue.runtime.esm-bundler.js:689
trigger @ vue.runtime.esm-bundler.js:659
set @ vue.runtime.esm-bundler.js:806
[...]

Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:421 Uncaught (in promise) TypeError: this.$slots.footer is not a function
    at Proxy.render (Calendar.vue_vue&type=style&index=0&id=0e88c5b9&lang-50d02b25.js:421:6)
    at Proxy.compatRender (vue.runtime.esm-bundler.js:8755:1)
    at renderComponentRoot (vue.runtime.esm-bundler.js:2865:1)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.runtime.esm-bundler.js:7672:1)
    at ReactiveEffect.run (vue.runtime.esm-bundler.js:491:1)
    at setupRenderEffect (vue.runtime.esm-bundler.js:7810:1)
    at mountComponent (vue.runtime.esm-bundler.js:7578:1)
    at processComponent (vue.runtime.esm-bundler.js:7532:1)
    at patch (vue.runtime.esm-bundler.js:7124:1)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.runtime.esm-bundler.js:7679:1)
```

**Comment by blaryj** [comment]
After cleaning all nodes_modules and reinstall, that's work fine. Sorry.

**Comment by kevintruby** [comment]
I am also using this project in a compatibility build, for a migration from Vue 2 to Vue 3. Seems reasonable that a non-trivial amount of other developers/groups will encounter migration headaches as well.

Perhaps this project should make sure all components define a `compatConfig: { MODE: 3 },` entry in the exported Options API structure.

This would have no impact on anyone using a standard Vue 3 setup, but would greatly benefit those of us who maintain larger applications.

In my case, we have been using just the `DatePicker` component -- you can sort of hack the component definition like so:

```javascript
components: {
  DatePicker: {
    ...DatePicker,
    compatConfig: {
      COMPONENT_V_MODEL: false,
      INSTANCE_SCOPED_SLOTS: false,
      RENDER_FUNCTION: false,
      MODE: 3,
    },
  },
},
```

But under the hood, it uses `Calendar` directly, and I can't force it to opt out of compatibility mode. I will be working around this via `patch-package` for now, but it would be extremely convenient to not rely on this.

Plus, when the Vue 3 version is stable, it's probably still going to need some way of supporting those using `@vue/compat`.

**Comment by elizatlawy** [comment]
Why is this ticket closed? this is still an issue.
